# Generated by Django 5.1.1 on 2025-04-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField()),
                ('PatID', models.IntegerField()),
                ('MName', models.CharField()),
                ('SName', models.CharField()),
                ('Age', models.FloatField()),
                ('DOB', models.DateTimeField()),
                ('city', models.FloatField()),
                ('Category', models.CharField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
