# Generated by Django 5.1.1 on 2025-04-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_alter_doctor_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Category',
        ),
        migrations.AddField(
            model_name='patient',
            name='categories',
            field=models.ManyToManyField(related_name='patients', to='Backend.category'),
        ),
    ]
